/*
* Copyright: (c) Mayo Foundation for Medical Education and
* Research (MFMER). All rights reserved. MAYO, MAYO CLINIC, and the
* triple-shield Mayo logo are trademarks and service marks of MFMER.
*
* Distributed under the OSI-approved BSD 3-Clause License.
* See http://ncip.github.com/lexevs-grid/LICENSE.txt for details.
*/
package org.LexGrid.LexBIG.cagrid.LexEVSGridService.service.globus;

import org.LexGrid.LexBIG.cagrid.Iso21090Utils;
import org.LexGrid.LexBIG.cagrid.LexEVSGridService.service.LexEVSGridServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the LexBIGCaGridServicesImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class LexEVSGridServiceProviderImpl{
	
	LexEVSGridServiceImpl impl;
	
	public LexEVSGridServiceProviderImpl() throws RemoteException {
		impl = new LexEVSGridServiceImpl();
	}
	

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSupportedCodingSchemesResponse getSupportedCodingSchemes(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSupportedCodingSchemesRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBInvocationException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSupportedCodingSchemesResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSupportedCodingSchemesResponse();
    boxedResult.setCodingSchemeRenderingList(impl.getSupportedCodingSchemes());
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetCodingSchemeConceptsResponse getCodingSchemeConcepts(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetCodingSchemeConceptsRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetCodingSchemeConceptsResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetCodingSchemeConceptsResponse();
    boxedResult.setCodedNodeSetReference(impl.getCodingSchemeConcepts(params.getCodingSchemeIdentification().getCodingSchemeIdentification(),params.getVersionOrTag().getCodingSchemeVersionOrTag()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeResponse resolveCodingScheme(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeResponse();
    boxedResult.setCodingScheme(impl.resolveCodingScheme(params.getCodingSchemeIdentification().getCodingSchemeIdentification(),params.getVersionOrTag().getCodingSchemeVersionOrTag()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetMatchAlgorithmsResponse getMatchAlgorithms(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetMatchAlgorithmsRequest params) throws RemoteException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetMatchAlgorithmsResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetMatchAlgorithmsResponse();
    boxedResult.setModuleDescriptionList(impl.getMatchAlgorithms());
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetNodeGraphResponse getNodeGraph(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetNodeGraphRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetNodeGraphResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetNodeGraphResponse();
    boxedResult.setCodedNodeGraphReference(impl.getNodeGraph(params.getCodingSchemeIdentification().getCodingSchemeIdentification(),params.getVersionOrTag().getCodingSchemeVersionOrTag(),params.getRelationContainerIdentification().getRelationContainerIdentification()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmsResponse getSortAlgorithms(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmsRequest params) throws RemoteException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmsResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmsResponse();
    boxedResult.setSortDescriptionList(impl.getSortAlgorithms(params.getContext()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionsResponse getGenericExtensions(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionsRequest params) throws RemoteException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionsResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionsResponse();
    boxedResult.setExtensionDescriptionList(impl.getGenericExtensions());
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionResponse getGenericExtension(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetGenericExtensionResponse();
    boxedResult.setLexBIGServiceConvenienceMethodsReference(impl.getGenericExtension(params.getExtensionIdentification().getExtensionIdentification()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterExtensionsResponse getFilterExtensions(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterExtensionsRequest params) throws RemoteException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterExtensionsResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterExtensionsResponse();
    boxedResult.setExtensionDescriptionList(impl.getFilterExtensions());
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetHistoryServiceResponse getHistoryService(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetHistoryServiceRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetHistoryServiceResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetHistoryServiceResponse();
    boxedResult.setHistoryServiceReference(impl.getHistoryService(params.getCodingSchemeIdentification().getCodingSchemeIdentification()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetServiceMetadataResponse getServiceMetadata(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetServiceMetadataRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetServiceMetadataResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetServiceMetadataResponse();
    boxedResult.setLexBIGServiceMetadataReference(impl.getServiceMetadata());
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmResponse getSortAlgorithm(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetSortAlgorithmResponse();
    boxedResult.setSortReference(impl.getSortAlgorithm(params.getExtensionIdentification().getExtensionIdentification()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterResponse getFilter(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.GetFilterResponse();
    boxedResult.setFilterReference(impl.getFilter(params.getExtensionIdentification().getExtensionIdentification()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeCopyrightResponse resolveCodingSchemeCopyright(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeCopyrightRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeCopyrightResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.ResolveCodingSchemeCopyrightResponse();
    boxedResult.setCodingSchemeCopyRight(impl.resolveCodingSchemeCopyright(params.getCodingSchemeIdentification().getCodingSchemeIdentification(),params.getVersionOrTag().getCodingSchemeVersionOrTag()));
    return boxedResult;
  }

    public org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.SetSecurityTokenResponse setSecurityToken(org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.SetSecurityTokenRequest params) throws RemoteException, org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.types.LBException {
    org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.SetSecurityTokenResponse boxedResult = new org.LexGrid.LexBIG.cagrid.LexEVSGridService.stubs.SetSecurityTokenResponse();
    boxedResult.setLexEVSGridServiceReference(impl.setSecurityToken(params.getCodingSchemeIdentification().getCodingSchemeIdentification(),params.getSecurityToken().getSecurityToken()));
    return boxedResult;
  }

}
